POST http://127.0.0.1:8000/main/addservice_with_video/
Content-Type: application/json

{
  "name": "Fitness Program",
  "content": "Workout for beginners",
  "date": "2025-09-20T18:00:00Z"
}

###
### Get all services
GET http://127.0.0.1:8000/main/services/

###
DELETE http://127.0.0.1:8000/main/delete_service/3/
Content-Type: application/json

{}
###
DELETE http://127.0.0.1:8000/main/delete_message/4/
Content-Type: application/json

{}
###

### Get all services
GET http://127.0.0.1:8000/main/messages/

###


awds hhuk dvnz fapi



### إرسال بريد اختبار
POST http://127.0.0.1:8000/main/send-test2-email/
Content-Type: application/json

{
  "subject": "ManUnited",
  "message": "2-0",
  "recipient": "nehadshretah@gmail.com"
}

############################
### Get CSRF token and page
GET http://127.0.0.1:8000/main/contact/
Accept: text/html

### Send message via JSON API
POST http://127.0.0.1:8000/main/send-message/
Content-Type: application/json

{
  "user_name": "MOHAMMED",
  "user_email": "markoriobrazil@gmail.com",
  "message": "322"
}

