POST http://127.0.0.1:8000/main/addservice_with_video/
Content-Type: application/json

{
  "name": "Fitness Program",
  "content": "Workout for beginners",
  "date": "2025-09-20T18:00:00Z"
}

###
### Get all services
GET http://127.0.0.1:8000/main/services/

###
DELETE http://127.0.0.1:8000/main/delete_service/3/
Content-Type: application/json

{}
###
DELETE http://127.0.0.1:8000/main/delete_message/4/
Content-Type: application/json

{}
###

### Get all services
GET http://127.0.0.1:8000/main/messages/

###


awds hhuk dvnz fapi



### إرسال بريد اختبار
POST http://127.0.0.1:8000/main/send-test2-email/
Content-Type: application/json

{
  "subject": "ManUnited",
  "message": "2-0",
  "recipient": "nehadshretah@gmail.com"
}

############################
### Get CSRF token and page
GET http://127.0.0.1:8000/main/contact/
Accept: text/html

### Send message via JSON API
POST http://127.0.0.1:8000/main/send-message/
Content-Type: application/json

{
  "user_name": "MOHAMMED",
  "user_email": "markoriobrazil@gmail.com",
  "message": "322"
}

#####
security way
#################################################################
POST http://127.0.0.1:8000/main/register/
Content-Type: application/json

{
  "email": "ali@example.com",
  "full_name": "ali",
  "password": "1234aliali",
  "password_confirm": "1234aliali"
}


### Login (Get Access + Refresh tokens)
POST http://127.0.0.1:8000/main/api/token/
Content-Type: application/json

{
  "email": "ali@example.com",
  "password": "1234aliali"
}


### Refresh Access Token
POST http://127.0.0.1:8000/main/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODgxNDYzOSwiaWF0IjoxNzU4ODE0NTE5LCJqdGkiOiI5ZGFiZWE2YWMyNjY0MzNmODM0MDZkYjBlYjU4ZjYxNSIsInVzZXJfaWQiOiIxIn0.CrS0-5Vu9GJuHy1ToHUwn3YIaiVOYrH-7Llviwxzkf8"
}


### Access private endpoint (replace {{access_token}} with real token)
GET http://127.0.0.1:8000/main/messages/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4ODE0NDY4LCJpYXQiOjE3NTg4MTQ0MDgsImp0aSI6ImMyOWY2MjM1YjVhMjQwMTQ4ZDc4ZjgxZTYwMmZjN2NkIiwidXNlcl9pZCI6IjEifQ.zalU4j-hcqA_lCYS658cLqNrsNhqV8obZvZTqeNhvww


### Try expired access token (should return 401)
GET http://127.0.0.1:8000/api/private/
Authorization: Bearer expired_or_fake_token


  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1ODgxNDQzMCwiaWF0IjoxNzU4ODE0MzEwLCJqdGkiOiIzOWM0MmRhMmM2MmI0MDJkOGMyNjZmMjgzNGQxMGJmYiIsInVzZXJfaWQiOiIxIn0.YG4SBZvLxXEGkTk-Mrct8ivROVGjB7uK2wb7fXiIxW4",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4ODE0MzcwLCJpYXQiOjE3NTg4MTQzMTAsImp0aSI6ImUzYjFiZWJiZmFkMzRhOTE5ZDhhZmUyMzg2YjIxNmVkIiwidXNlcl9pZCI6IjEifQ.lK44EUVpsCAIZpbmer2iLOX4YH9F3MXpUAE0gLnlbd4"


### Change password with email
POST http://127.0.0.1:8000/main/change-password/
Content-Type: application/json

{
  "email": "ali@example.com",
  "old_password": "1234aliali",
  "new_password": "2345aliali",
  "new_password_confirm": "2345aliali"
}

### Check credentials (email + password)  <-- the endpoint you asked for
POST http://127.0.0.1:8000/main/api/check-credentials/
Content-Type: application/json

{
  "email": "ali@example.com",
  "password": "2345aliali"
}